# Generated by Django 4.2 on 2023-05-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('edad', models.CharField(max_length=2)),
                ('rol', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=10)),
                ('clave', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=2)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('caracteristicas', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=3)),
                ('cedula_dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.usuario')),
            ],
        ),
    ]
