# Generated by Django 4.2 on 2023-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0003_alter_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
