# Generated by Django 4.2 on 2023-05-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0006_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50, null=True)),
                ('valor', models.FloatField(max_length=15)),
                ('cantidad', models.IntegerField(max_length=5)),
                ('cedula_dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.usuario')),
                ('cedula_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.orden')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.mascota')),
            ],
        ),
    ]
