# Generated by Django 4.2 on 2023-05-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0007_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='fecha',
        ),
    ]
