# Generated by Django 4.2 on 2023-05-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0008_remove_orden_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
