# Generated by Django 4.2 on 2023-05-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0009_alter_factura_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='cedula_orden',
            new_name='id_orden',
        ),
    ]
