# Generated by Django 4.2 on 2023-05-23 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0011_alter_usuario_clave_alter_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
