# Generated by Django 4.2 on 2023-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0012_orden_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
