# Generated by Django 4.2 on 2023-05-25 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appVeterinaria', '0014_orden_anulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appVeterinaria.orden'),
        ),
    ]
